// Catálogo Alexandrix Books — obras integrais em português (domínio público)
export type Book = {
  id: number;
  gutenbergId: number;
  title: string;
  author: string;
  genre: string;
  year: number;
  cover: string;
  color: [string, string];
  desc: string;
};

export const books: Book[] = [
  {"id": 1, "gutenbergId": 55752, "title": "Dom Casmurro", "author": "Machado de Assis", "genre": "Clássico", "year": 1899, "cover": "https://www.gutenberg.org/cache/epub/55752/pg55752.cover.medium.jpg", "color": ["#3a2c5e", "#150f2e"], "desc": "Bentinho recorda a paixão por Capitu e a dúvida que envenena tudo — o maior romance da literatura brasileira."},
  {"id": 2, "gutenbergId": 54829, "title": "Memórias Póstumas de Brás Cubas", "author": "Machado de Assis", "genre": "Clássico", "year": 1881, "cover": "https://www.gutenberg.org/cache/epub/54829/pg54829.cover.medium.jpg", "color": ["#3a2c5e", "#150f2e"], "desc": "Um defunto autor narra a própria vida com ironia impiedosa. Marco inaugural do realismo no Brasil."},
  {"id": 3, "gutenbergId": 55682, "title": "Quincas Borba", "author": "Machado de Assis", "genre": "Clássico", "year": 1891, "cover": "https://www.gutenberg.org/cache/epub/55682/pg55682.cover.medium.jpg", "color": ["#3a2c5e", "#150f2e"], "desc": "Rubião herda uma fortuna e a filosofia do Humanitismo — e enlouquece devagar entre salões e ilusões."},
  {"id": 4, "gutenbergId": 56737, "title": "Esaú e Jacó", "author": "Machado de Assis", "genre": "Clássico", "year": 1904, "cover": "https://www.gutenberg.org/cache/epub/56737/pg56737.cover.medium.jpg", "color": ["#3a2c5e", "#150f2e"], "desc": "Os gêmeos Pedro e Paulo disputam tudo, inclusive o amor de Flora, na passagem do Império à República."},
  {"id": 5, "gutenbergId": 55797, "title": "Memorial de Aires", "author": "Machado de Assis", "genre": "Clássico", "year": 1908, "cover": "https://www.gutenberg.org/cache/epub/55797/pg55797.cover.medium.jpg", "color": ["#3a2c5e", "#150f2e"], "desc": "O diário do conselheiro Aires, último livro de Machado: melancolia, memória e delicadeza."},
  {"id": 6, "gutenbergId": 67162, "title": "Helena", "author": "Machado de Assis", "genre": "Romance", "year": 1876, "cover": "https://www.gutenberg.org/cache/epub/67162/pg67162.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Um testamento revela uma irmã desconhecida — segredo, honra e amor proibido no Rio imperial."},
  {"id": 7, "gutenbergId": 53101, "title": "A Mão e a Luva", "author": "Machado de Assis", "genre": "Romance", "year": 1874, "cover": "https://www.gutenberg.org/cache/epub/53101/pg53101.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Guiomar escolhe entre pretendentes e ambições: um retrato fino da vontade feminina."},
  {"id": 8, "gutenbergId": 67780, "title": "Iaiá Garcia", "author": "Machado de Assis", "genre": "Romance", "year": 1878, "cover": "https://www.gutenberg.org/cache/epub/67780/pg67780.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Amor, dever e sacrifício se cruzam na história de Estela, Jorge e Iaiá Garcia."},
  {"id": 9, "gutenbergId": 57001, "title": "Papéis Avulsos", "author": "Machado de Assis", "genre": "Contos", "year": 1882, "cover": "https://www.gutenberg.org/cache/epub/57001/pg57001.cover.medium.jpg", "color": ["#1c4a5e", "#08202e"], "desc": "Reúne \"O Alienista\" e \"O Espelho\" — a face mais experimental e satírica de Machado."},
  {"id": 10, "gutenbergId": 33056, "title": "Histórias sem Data", "author": "Machado de Assis", "genre": "Contos", "year": 1884, "cover": "https://www.gutenberg.org/cache/epub/33056/pg33056.cover.medium.jpg", "color": ["#1c4a5e", "#08202e"], "desc": "Contos memoráveis sobre casamento, vaidade e o absurdo cotidiano."},
  {"id": 11, "gutenbergId": 67935, "title": "Relíquias de Casa Velha", "author": "Machado de Assis", "genre": "Contos", "year": 1906, "cover": "https://www.gutenberg.org/cache/epub/67935/pg67935.cover.medium.jpg", "color": ["#1c4a5e", "#08202e"], "desc": "Contos, versos e teatro reunidos pelo próprio autor no fim da vida."},
  {"id": 12, "gutenbergId": 61653, "title": "Poesias Completas", "author": "Machado de Assis", "genre": "Poesia", "year": 1901, "cover": "https://www.gutenberg.org/cache/epub/61653/pg61653.cover.medium.jpg", "color": ["#2c1c5e", "#0d0724"], "desc": "Crisálidas, Falenas, Americanas e Ocidentais: toda a poesia machadiana."},
  {"id": 13, "gutenbergId": 40409, "title": "Os Maias", "author": "Eça de Queirós", "genre": "Clássico", "year": 1888, "cover": "https://www.gutenberg.org/cache/epub/40409/pg40409.cover.medium.jpg", "color": ["#3a2c5e", "#150f2e"], "desc": "A decadência de uma família aristocrática e o retrato feroz da Lisboa do século XIX."},
  {"id": 14, "gutenbergId": 31971, "title": "O Crime do Padre Amaro", "author": "Eça de Queirós", "genre": "Clássico", "year": 1875, "cover": "https://www.gutenberg.org/cache/epub/31971/pg31971.cover.medium.jpg", "color": ["#3a2c5e", "#150f2e"], "desc": "Um padre jovem, uma paixão proibida e a hipocrisia de uma cidade provinciana."},
  {"id": 15, "gutenbergId": 42942, "title": "O Primo Basílio", "author": "Eça de Queirós", "genre": "Clássico", "year": 1878, "cover": "https://www.gutenberg.org/cache/epub/42942/pg42942.cover.medium.jpg", "color": ["#3a2c5e", "#150f2e"], "desc": "Luísa, o marido ausente e o primo sedutor: adultério e chantagem na burguesia lisboeta."},
  {"id": 16, "gutenbergId": 23145, "title": "A Ilustre Casa de Ramires", "author": "Eça de Queirós", "genre": "Romance", "year": 1900, "cover": "https://www.gutenberg.org/cache/epub/23145/pg23145.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Gonçalo Mendes Ramires tenta escrever a glória dos antepassados enquanto sua vida desmorona."},
  {"id": 17, "gutenbergId": 18220, "title": "A Cidade e as Serras", "author": "Eça de Queirós", "genre": "Romance", "year": 1901, "cover": "https://www.gutenberg.org/cache/epub/18220/pg18220.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Jacinto troca o luxo de Paris pela serra portuguesa e descobre outra ideia de felicidade."},
  {"id": 18, "gutenbergId": 17515, "title": "A Relíquia", "author": "Eça de Queirós", "genre": "Romance", "year": 1887, "cover": "https://www.gutenberg.org/cache/epub/17515/pg17515.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Teodorico finge devoção para herdar a fortuna da tia — satira brilhante da beatice."},
  {"id": 19, "gutenbergId": 16384, "title": "O Mandarim", "author": "Eça de Queirós", "genre": "Romance", "year": 1880, "cover": "https://www.gutenberg.org/cache/epub/16384/pg16384.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Um pequeno funcionário mata um mandarim chinês por dinheiro e é perseguido pela culpa."},
  {"id": 20, "gutenbergId": 31347, "title": "Contos", "author": "Eça de Queirós", "genre": "Contos", "year": 1902, "cover": "https://www.gutenberg.org/cache/epub/31347/pg31347.cover.medium.jpg", "color": ["#1c4a5e", "#08202e"], "desc": "\"Singularidades de uma Rapariga Loura\", \"José Matias\" e outras obras-primas curtas."},
  {"id": 21, "gutenbergId": 20574, "title": "O Mistério da Estrada de Sintra", "author": "Eça de Queirós", "genre": "Mistério", "year": 1870, "cover": "https://www.gutenberg.org/cache/epub/20574/pg20574.cover.medium.jpg", "color": ["#2c2c2c", "#0a0a0a"], "desc": "Escrito a quatro mãos com Ramalho Ortigão: o primeiro grande romance policial português."},
  {"id": 22, "gutenbergId": 67740, "title": "Iracema", "author": "José de Alencar", "genre": "Romance", "year": 1865, "cover": "https://www.gutenberg.org/cache/epub/67740/pg67740.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "A lenda da virgem dos lábios de mel e do guerreiro branco — mito de fundação do Brasil."},
  {"id": 23, "gutenbergId": 67724, "title": "O Guarani — Volume 1", "author": "José de Alencar", "genre": "Romance", "year": 1857, "cover": "https://www.gutenberg.org/cache/epub/67724/pg67724.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Peri, Ceci e a floresta: o romance indianista que definiu o romantismo brasileiro."},
  {"id": 24, "gutenbergId": 67725, "title": "O Guarani — Volume 2", "author": "José de Alencar", "genre": "Romance", "year": 1857, "cover": "https://www.gutenberg.org/cache/epub/67725/pg67725.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "A conclusão da saga de Peri e Ceci, entre lealdade, honra e destino."},
  {"id": 25, "gutenbergId": 38496, "title": "Ubirajara", "author": "José de Alencar", "genre": "Romance", "year": 1874, "cover": "https://www.gutenberg.org/cache/epub/38496/pg38496.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Uma epopeia tupi sobre coragem, nome e pertencimento antes da chegada dos europeus."},
  {"id": 26, "gutenbergId": 44540, "title": "Cinco Minutos", "author": "José de Alencar", "genre": "Romance", "year": 1856, "cover": "https://www.gutenberg.org/cache/epub/44540/pg44540.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Cinco minutos de atraso mudam um destino: a primeira novela de Alencar."},
  {"id": 27, "gutenbergId": 67831, "title": "A Pata da Gazela", "author": "José de Alencar", "genre": "Romance", "year": 1870, "cover": "https://www.gutenberg.org/cache/epub/67831/pg67831.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Um pé delicado, um sapato perdido e uma obsessão elegante na corte carioca."},
  {"id": 28, "gutenbergId": 69187, "title": "O Cortiço", "author": "Aluísio Azevedo", "genre": "Clássico", "year": 1890, "cover": "https://www.gutenberg.org/cache/epub/69187/pg69187.cover.medium.jpg", "color": ["#3a2c5e", "#150f2e"], "desc": "João Romão, Rita Baiana e o formigueiro humano de um cortiço carioca: naturalismo em estado puro."},
  {"id": 29, "gutenbergId": 67535, "title": "Triste Fim de Policarpo Quaresma", "author": "Lima Barreto", "genre": "Clássico", "year": 1915, "cover": "https://www.gutenberg.org/cache/epub/67535/pg67535.cover.medium.jpg", "color": ["#3a2c5e", "#150f2e"], "desc": "O patriota ingênuo que queria salvar o Brasil — humor e amargura sobre o país que não o merecia."},
  {"id": 30, "gutenbergId": 68541, "title": "O Ateneu", "author": "Raul Pompéia", "genre": "Clássico", "year": 1888, "cover": "https://www.gutenberg.org/cache/epub/68541/pg68541.cover.medium.jpg", "color": ["#3a2c5e", "#150f2e"], "desc": "Sérgio recorda o internato: crueldade, hierarquia e perda da inocência."},
  {"id": 31, "gutenbergId": 16425, "title": "Amor de Perdição", "author": "Camilo Castelo Branco", "genre": "Romance", "year": 1862, "cover": "https://www.gutenberg.org/cache/epub/16425/pg16425.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Simão e Teresa: o mais célebre romance trágico português, escrito na prisão."},
  {"id": 32, "gutenbergId": 17927, "title": "A Queda dum Anjo", "author": "Camilo Castelo Branco", "genre": "Romance", "year": 1866, "cover": "https://www.gutenberg.org/cache/epub/17927/pg17927.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Um fidalgo provinciano vira deputado em Lisboa e perde a alma no caminho."},
  {"id": 33, "gutenbergId": 21406, "title": "Novelas do Minho", "author": "Camilo Castelo Branco", "genre": "Contos", "year": 1875, "cover": "https://www.gutenberg.org/cache/epub/21406/pg21406.cover.medium.jpg", "color": ["#1c4a5e", "#08202e"], "desc": "Histórias duras e vivíssimas da gente do campo minhoto."},
  {"id": 34, "gutenbergId": 68905, "title": "A Brasileira de Prazins", "author": "Camilo Castelo Branco", "genre": "Romance", "year": 1882, "cover": "https://www.gutenberg.org/cache/epub/68905/pg68905.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Marta e o retorno do \"brasileiro\" rico: superstição, ciúme e loucura no Minho."},
  {"id": 35, "gutenbergId": 3333, "title": "Os Lusíadas", "author": "Luís de Camões", "genre": "Poesia", "year": 1572, "cover": "https://www.gutenberg.org/cache/epub/3333/pg3333.cover.medium.jpg", "color": ["#2c1c5e", "#0d0724"], "desc": "A epopeia da navegação portuguesa — o maior poema épico da língua portuguesa."},
  {"id": 36, "gutenbergId": 24401, "title": "Viagens na Minha Terra", "author": "Almeida Garrett", "genre": "Crônica", "year": 1846, "cover": "https://www.gutenberg.org/cache/epub/24401/pg24401.cover.medium.jpg", "color": ["#4a1c4a", "#1a0a20"], "desc": "Uma viagem de Lisboa a Santarém que é, na verdade, uma viagem pelas ideias do século."},
  {"id": 37, "gutenbergId": 17591, "title": "Frei Luís de Sousa", "author": "Almeida Garrett", "genre": "Teatro", "year": 1844, "cover": "https://www.gutenberg.org/cache/epub/17591/pg17591.cover.medium.jpg", "color": ["#5e2c1c", "#220e08"], "desc": "A tragédia de Madalena e o regresso do marido dado por morto: teatro romântico perfeito."},
  {"id": 38, "gutenbergId": 9654, "title": "Lendas e Narrativas — Tomo I", "author": "Alexandre Herculano", "genre": "Contos", "year": 1851, "cover": "https://www.gutenberg.org/cache/epub/9654/pg9654.cover.medium.jpg", "color": ["#1c4a5e", "#08202e"], "desc": "Lendas medievais portuguesas contadas com fôlego de romance histórico."},
  {"id": 39, "gutenbergId": 17005, "title": "Lendas e Narrativas — Tomo II", "author": "Alexandre Herculano", "genre": "Contos", "year": 1851, "cover": "https://www.gutenberg.org/cache/epub/17005/pg17005.cover.medium.jpg", "color": ["#1c4a5e", "#08202e"], "desc": "Segunda parte das narrativas históricas que fundaram o romance em Portugal."},
  {"id": 40, "gutenbergId": 29120, "title": "A Morgadinha dos Canaviais", "author": "Júlio Dinis", "genre": "Romance", "year": 1868, "cover": "https://www.gutenberg.org/cache/epub/29120/pg29120.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Madalena, a aldeia e o progresso: o mais querido romance de costumes português."},
  {"id": 41, "gutenbergId": 16428, "title": "Os Fidalgos da Casa Mourisca", "author": "Júlio Dinis", "genre": "Romance", "year": 1871, "cover": "https://www.gutenberg.org/cache/epub/16428/pg16428.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Duas gerações em conflito entre a tradição fidalga e o trabalho moderno."},
  {"id": 42, "gutenbergId": 16443, "title": "Uma Família Inglesa", "author": "Júlio Dinis", "genre": "Romance", "year": 1868, "cover": "https://www.gutenberg.org/cache/epub/16443/pg16443.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Amor, comércio e honra na cidade do Porto do século XIX."},
  {"id": 43, "gutenbergId": 20142, "title": "Sonetos Completos", "author": "Antero de Quental", "genre": "Poesia", "year": 1886, "cover": "https://www.gutenberg.org/cache/epub/20142/pg20142.cover.medium.jpg", "color": ["#2c1c5e", "#0d0724"], "desc": "A poesia filosófica e angustiada do maior sonetista português moderno."},
  {"id": 44, "gutenbergId": 8698, "title": "O Livro de Cesário Verde", "author": "Cesário Verde", "genre": "Poesia", "year": 1887, "cover": "https://www.gutenberg.org/cache/epub/8698/pg8698.cover.medium.jpg", "color": ["#2c1c5e", "#0d0724"], "desc": "Lisboa vista com olho de pintor: o poeta que inventou a modernidade em português."},
  {"id": 45, "gutenbergId": 21799, "title": "Dispersão", "author": "Mário de Sá-Carneiro", "genre": "Poesia", "year": 1914, "cover": "https://www.gutenberg.org/cache/epub/21799/pg21799.cover.medium.jpg", "color": ["#2c1c5e", "#0d0724"], "desc": "Doze poemas de vertigem e desdobramento — o modernismo português em carne viva."},
  {"id": 46, "gutenbergId": 17193, "title": "Só", "author": "António Nobre", "genre": "Poesia", "year": 1892, "cover": "https://www.gutenberg.org/cache/epub/17193/pg17193.cover.medium.jpg", "color": ["#2c1c5e", "#0d0724"], "desc": "Saudade, infância e província no livro mais melancólico da poesia portuguesa."},
  {"id": 47, "gutenbergId": 21209, "title": "Pátria", "author": "Guerra Junqueiro", "genre": "Poesia", "year": 1896, "cover": "https://www.gutenberg.org/cache/epub/21209/pg21209.cover.medium.jpg", "color": ["#2c1c5e", "#0d0724"], "desc": "Poema dramático e incendiário sobre a decadência da nação."},
  {"id": 48, "gutenbergId": 23526, "title": "A Velhice do Padre Eterno", "author": "Guerra Junqueiro", "genre": "Poesia", "year": 1885, "cover": "https://www.gutenberg.org/cache/epub/23526/pg23526.cover.medium.jpg", "color": ["#2c1c5e", "#0d0724"], "desc": "Satira anticlerical que escandalizou Portugal e virou clássico."},
  {"id": 49, "gutenbergId": 16429, "title": "Contos para a Infância", "author": "Guerra Junqueiro", "genre": "Infantojuvenil", "year": 1877, "cover": "https://www.gutenberg.org/cache/epub/16429/pg16429.cover.medium.jpg", "color": ["#5e4a1c", "#241a06"], "desc": "Seleção de contos e fábulas para os primeiros leitores."},
  {"id": 50, "gutenbergId": 30510, "title": "Pérolas e Diamantes: Contos Infantis", "author": "Irmãos Grimm", "genre": "Infantojuvenil", "year": 1812, "cover": "https://www.gutenberg.org/cache/epub/30510/pg30510.cover.medium.jpg", "color": ["#5e4a1c", "#241a06"], "desc": "Os contos de fadas dos Grimm em edição portuguesa ilustrada."},
  {"id": 51, "gutenbergId": 39618, "title": "Humus", "author": "Raul Brandão", "genre": "Clássico", "year": 1917, "cover": "https://www.gutenberg.org/cache/epub/39618/pg39618.cover.medium.jpg", "color": ["#3a2c5e", "#150f2e"], "desc": "A vila, os mortos e o tédio: prosa poética alucinada e absolutamente moderna."},
  {"id": 52, "gutenbergId": 20841, "title": "Os Pobres", "author": "Raul Brandão", "genre": "Romance", "year": 1906, "cover": "https://www.gutenberg.org/cache/epub/20841/pg20841.cover.medium.jpg", "color": ["#5e1c3a", "#22091a"], "desc": "Três vidas miseráveis contadas com uma compaixão que dói."},
  {"id": 53, "gutenbergId": 28341, "title": "Da Terra à Lua", "author": "Júlio Verne", "genre": "Ficção Científica", "year": 1865, "cover": "https://www.gutenberg.org/cache/epub/28341/pg28341.cover.medium.jpg", "color": ["#0a3a5e", "#001830"], "desc": "Um canhão gigante lança três homens à Lua — a ficção científica antes dos foguetes."},
  {"id": 54, "gutenbergId": 62101, "title": "Robur, o Conquistador", "author": "Júlio Verne", "genre": "Ficção Científica", "year": 1886, "cover": "https://www.gutenberg.org/cache/epub/62101/pg62101.cover.medium.jpg", "color": ["#0a3a5e", "#001830"], "desc": "O engenheiro Robur prova que o futuro do voo é mais pesado que o ar."},
  {"id": 55, "gutenbergId": 22015, "title": "As Minas de Salomão", "author": "H. Rider Haggard", "genre": "Aventura", "year": 1885, "cover": "https://www.gutenberg.org/cache/epub/22015/pg22015.cover.medium.jpg", "color": ["#1c5e3a", "#07240f"], "desc": "Tradução célebre de Eça de Queirós para a caçada ao tesouro perdido na África."},
  {"id": 56, "gutenbergId": 25667, "title": "Hamlet", "author": "William Shakespeare", "genre": "Teatro", "year": 1603, "cover": "https://www.gutenberg.org/cache/epub/25667/pg25667.cover.medium.jpg", "color": ["#5e2c1c", "#220e08"], "desc": "Ser ou não ser: a tragédia do príncipe da Dinamarca, em tradução portuguesa."},
  {"id": 57, "gutenbergId": 28526, "title": "Otelo", "author": "William Shakespeare", "genre": "Teatro", "year": 1604, "cover": "https://www.gutenberg.org/cache/epub/28526/pg28526.cover.medium.jpg", "color": ["#5e2c1c", "#220e08"], "desc": "Ciúme, manipulação e destruição — Iago sussurra e um mundo desaba."},
  {"id": 58, "gutenbergId": 17503, "title": "Os Meus Amores", "author": "Trindade Coelho", "genre": "Contos", "year": 1891, "cover": "https://www.gutenberg.org/cache/epub/17503/pg17503.cover.medium.jpg", "color": ["#1c4a5e", "#08202e"], "desc": "Contos e baladas do interior português, ternos e exatos."},
  {"id": 59, "gutenbergId": 32646, "title": "Contos Fantásticos", "author": "Teófilo Braga", "genre": "Contos", "year": 1865, "cover": "https://www.gutenberg.org/cache/epub/32646/pg32646.cover.medium.jpg", "color": ["#1c4a5e", "#08202e"], "desc": "Narrativas fantásticas e populares recolhidas e recriadas."},
  {"id": 60, "gutenbergId": 70819, "title": "Contos", "author": "Fialho de Almeida", "genre": "Contos", "year": 1881, "cover": "https://www.gutenberg.org/cache/epub/70819/pg70819.cover.medium.jpg", "color": ["#1c4a5e", "#08202e"], "desc": "Prosa cruel e luminosa de um dos grandes contistas portugueses."},
  {"id": 61, "gutenbergId": 74854, "title": "Cantos", "author": "Gonçalves Dias", "genre": "Poesia", "year": 1846, "cover": "https://www.gutenberg.org/cache/epub/74854/pg74854.cover.medium.jpg", "color": ["#2c1c5e", "#0d0724"], "desc": "\"Canção do Exílio\" e os poemas que deram voz ao romantismo brasileiro."},
  {"id": 62, "gutenbergId": 30359, "title": "Contos e Lendas", "author": "Rebelo da Silva", "genre": "Contos", "year": 1873, "cover": "https://www.gutenberg.org/cache/epub/30359/pg30359.cover.medium.jpg", "color": ["#1c4a5e", "#08202e"], "desc": "Lendas históricas e quadros de costumes do romantismo português."},
  {"id": 63, "gutenbergId": 63317, "title": "Os Contos do Tio Joaquim", "author": "Rodrigo Paganino", "genre": "Contos", "year": 1861, "cover": "https://www.gutenberg.org/cache/epub/63317/pg63317.cover.medium.jpg", "color": ["#1c4a5e", "#08202e"], "desc": "Histórias rurais contadas por um tio sábio — clássico da literatura popular."},
  {"id": 64, "gutenbergId": 24190, "title": "No País dos Ianques", "author": "Adolfo Caminha", "genre": "Crônica", "year": 1894, "cover": "https://www.gutenberg.org/cache/epub/24190/pg24190.cover.medium.jpg", "color": ["#4a1c4a", "#1a0a20"], "desc": "O relato vivo de um marinheiro brasileiro nos Estados Unidos do século XIX."},
];
